all:
	cd adjust & nmake /nologo
	cd adphas & nmake /nologo
	cd AFM & nmake /nologo
	cd armand & nmake /nologo
	cd arrowdesign & nmake /nologo
	cd arrowstyle & nmake /nologo
	cd ascatterplot & nmake /nologo
	cd bar3d & nmake /nologo
	cd barchart & nmake /nologo
	cd barcode_example & nmake /nologo
	cd bayesiannet & nmake /nologo
	cd bindots & nmake /nologo
	cd binning & nmake /nologo
	cd bitmap & nmake /nologo
	cd boxplot & nmake /nologo
	cd boxplot-ft & nmake /nologo
	cd brilzone & nmake /nologo
	cd bspline & nmake /nologo
	cd bubble & nmake /nologo
	cd bumpchart & nmake /nologo
	cd business_cards_10_per_A4 & nmake /nologo
	cd butterfly & nmake /nologo
	cd cavity & nmake /nologo
	cd circuit1 & nmake /nologo
	cd circuit2 & nmake /nologo
	cd circuit3 & nmake /nologo
	cd circuit4 & nmake /nologo
	cd clip & nmake /nologo
	cd clip-ft & nmake /nologo
	cd color-markers-3d & nmake /nologo
	cd colorbar & nmake /nologo
	cd colormap & nmake /nologo
	cd colormapcontour & nmake /nologo
	cd colorspaces & nmake /nologo
	cd color_list_svg & nmake /nologo
	cd color_sample & nmake /nologo
	cd compactkey & nmake /nologo
	cd corrs & nmake /nologo
	cd cos2t & nmake /nologo
	cd crispdm & nmake /nologo
	cd curve & nmake /nologo
	cd curvedarrow & nmake /nologo
	cd data & nmake /nologo
	cd decay & nmake /nologo
	cd diffeq & nmake /nologo
	cd discontinuity & nmake /nologo
	cd dragon & nmake /nologo
	cd drawpie & nmake /nologo
	cd dvifill & nmake /nologo
	cd ellipsearrow & nmake /nologo
	cd ellipses & nmake /nologo
	cd elliptical_arcs & nmake /nologo
	cd entropy & nmake /nologo
	cd equation & nmake /nologo
	cd errors & nmake /nologo
	cd f-f2 & nmake /nologo
	cd feynman_1 & nmake /nologo
	cd feynman_10 & nmake /nologo
	cd feynman_11 & nmake /nologo
	cd feynman_12 & nmake /nologo
	cd feynman_13 & nmake /nologo
	cd feynman_14 & nmake /nologo
	cd feynman_15 & nmake /nologo
	cd feynman_16 & nmake /nologo
	cd feynman_17 & nmake /nologo
	cd feynman_18 & nmake /nologo
	cd feynman_19 & nmake /nologo
	cd feynman_2 & nmake /nologo
	cd feynman_3 & nmake /nologo
	cd feynman_4 & nmake /nologo
	cd feynman_5 & nmake /nologo
	cd feynman_6 & nmake /nologo
	cd feynman_7 & nmake /nologo
	cd feynman_8 & nmake /nologo
	cd feynman_9 & nmake /nologo
	cd feynman_shadow & nmake /nologo
	cd feynman_test & nmake /nologo
	cd fill & nmake /nologo
	cd fill-ft & nmake /nologo
	cd filters81 & nmake /nologo
	cd fitls & nmake /nologo
	cd fitz & nmake /nologo
	cd flow & nmake /nologo
	cd flux_linkage_space_vector_diagram & nmake /nologo
	cd four & nmake /nologo
	cd frequency & nmake /nologo
	cd fruitbar & nmake /nologo
	cd gc_color & nmake /nologo
	cd gc_join & nmake /nologo
	cd gc_write & nmake /nologo
	cd gradient & nmake /nologo
	cd h-bridge & nmake /nologo
	cd heatmap & nmake /nologo
	cd hello & nmake /nologo
	cd histogram & nmake /nologo
	cd horizon & nmake /nologo
	cd house & nmake /nologo
	cd hubble & nmake /nologo
	cd hyperbola & nmake /nologo
	cd informationgain & nmake /nologo
	cd inpstm & nmake /nologo
	cd intersect & nmake /nologo
	cd jitter & nmake /nologo
	cd join & nmake /nologo
	cd keyexamples & nmake /nologo
	cd koch & nmake /nologo
	cd labeled-scatter & nmake /nologo
	cd labels & nmake /nologo
	cd legend & nmake /nologo
	cd let-multi-dim & nmake /nologo
	cd lindenmayer & nmake /nologo
	cd line & nmake /nologo
	cd linemode & nmake /nologo
	cd lines & nmake /nologo
	cd lnx & nmake /nologo
	cd logo & nmake /nologo
	cd loop & nmake /nologo
	cd M16 & nmake /nologo
	cd M4_Re_Im & nmake /nologo
	cd mandelbrot & nmake /nologo
	cd margins & nmake /nologo
	cd markers & nmake /nologo
	cd math & nmake /nologo
	cd maungazoom & nmake /nologo
	cd mirrors & nmake /nologo
	cd mutation & nmake /nologo
	cd normal & nmake /nologo
	cd objects & nmake /nologo
	cd opening & nmake /nologo
	cd perceptron & nmake /nologo
	cd phasedemo & nmake /nologo
	cd playtennis_dt & nmake /nologo
	cd polarcircle & nmake /nologo
	cd polargrid & nmake /nologo
	cd polar_histogram & nmake /nologo
	cd polenja & nmake /nologo
	cd protract & nmake /nologo
	cd pythagoras & nmake /nologo
	cd pythagorean & nmake /nologo
	cd qgle_keyboard & nmake /nologo
	cd quantilescale & nmake /nologo
	cd radar & nmake /nologo
	cd ramps & nmake /nologo
	cd recursiontree & nmake /nologo
	cd regrmodel & nmake /nologo
	cd rt-y-is-x & nmake /nologo
	cd rugplot & nmake /nologo
	cd saddle & nmake /nologo
	cd saddle-contour & nmake /nologo
	cd sarppepo & nmake /nologo
	cd SdHmethod & nmake /nologo
	cd seaborn & nmake /nologo
	cd semitrans & nmake /nologo
	cd series & nmake /nologo
	cd shadebar & nmake /nologo
	cd shadow & nmake /nologo
	cd shapes & nmake /nologo
	cd shapes-ft & nmake /nologo
	cd sierpinski & nmake /nologo
	cd sin & nmake /nologo
	cd sine-approx & nmake /nologo
	cd spider & nmake /nologo
	cd sqroot & nmake /nologo
	cd square & nmake /nologo
	cd stack1 & nmake /nologo
	cd stack2 & nmake /nologo
	cd stack4b & nmake /nologo
	cd stack4c & nmake /nologo
	cd stacks & nmake /nologo
	cd steps & nmake /nologo
	cd stuff & nmake /nologo
	cd super-ellipse & nmake /nologo
	cd testaccents & nmake /nologo
	cd texgraph & nmake /nologo
	cd tgplot & nmake /nologo
	cd tree & nmake /nologo
	cd utitle & nmake /nologo
	cd volcano & nmake /nologo
	cd volcano-ft & nmake /nologo
	cd volcano3d & nmake /nologo
	cd wall & nmake /nologo
	cd wallx & nmake /nologo
	cd web & nmake /nologo
	cd winding & nmake /nologo
	cd windrose & nmake /nologo
	cd wulfnet & nmake /nologo
	cd zoom-in & nmake /nologo

clean:
	cd adjust & nmake /nologo clean
	cd adphas & nmake /nologo clean
	cd AFM & nmake /nologo clean
	cd armand & nmake /nologo clean
	cd arrowdesign & nmake /nologo clean
	cd arrowstyle & nmake /nologo clean
	cd ascatterplot & nmake /nologo clean
	cd bar3d & nmake /nologo clean
	cd barchart & nmake /nologo clean
	cd barcode_example & nmake /nologo clean
	cd bayesiannet & nmake /nologo clean
	cd bindots & nmake /nologo clean
	cd binning & nmake /nologo clean
	cd bitmap & nmake /nologo clean
	cd boxplot & nmake /nologo clean
	cd boxplot-ft & nmake /nologo clean
	cd brilzone & nmake /nologo clean
	cd bspline & nmake /nologo clean
	cd bubble & nmake /nologo clean
	cd bumpchart & nmake /nologo clean
	cd business_cards_10_per_A4 & nmake /nologo clean
	cd butterfly & nmake /nologo clean
	cd cavity & nmake /nologo clean
	cd circuit1 & nmake /nologo clean
	cd circuit2 & nmake /nologo clean
	cd circuit3 & nmake /nologo clean
	cd circuit4 & nmake /nologo clean
	cd clip & nmake /nologo clean
	cd clip-ft & nmake /nologo clean
	cd color-markers-3d & nmake /nologo clean
	cd colorbar & nmake /nologo clean
	cd colormap & nmake /nologo clean
	cd colormapcontour & nmake /nologo clean
	cd colorspaces & nmake /nologo clean
	cd color_list_svg & nmake /nologo clean
	cd color_sample & nmake /nologo clean
	cd compactkey & nmake /nologo clean
	cd corrs & nmake /nologo clean
	cd cos2t & nmake /nologo clean
	cd crispdm & nmake /nologo clean
	cd curve & nmake /nologo clean
	cd curvedarrow & nmake /nologo clean
	cd data & nmake /nologo clean
	cd decay & nmake /nologo clean
	cd diffeq & nmake /nologo clean
	cd discontinuity & nmake /nologo clean
	cd dragon & nmake /nologo clean
	cd drawpie & nmake /nologo clean
	cd dvifill & nmake /nologo clean
	cd ellipsearrow & nmake /nologo clean
	cd ellipses & nmake /nologo clean
	cd elliptical_arcs & nmake /nologo clean
	cd entropy & nmake /nologo clean
	cd equation & nmake /nologo clean
	cd errors & nmake /nologo clean
	cd f-f2 & nmake /nologo clean
	cd feynman_1 & nmake /nologo clean
	cd feynman_10 & nmake /nologo clean
	cd feynman_11 & nmake /nologo clean
	cd feynman_12 & nmake /nologo clean
	cd feynman_13 & nmake /nologo clean
	cd feynman_14 & nmake /nologo clean
	cd feynman_15 & nmake /nologo clean
	cd feynman_16 & nmake /nologo clean
	cd feynman_17 & nmake /nologo clean
	cd feynman_18 & nmake /nologo clean
	cd feynman_19 & nmake /nologo clean
	cd feynman_2 & nmake /nologo clean
	cd feynman_3 & nmake /nologo clean
	cd feynman_4 & nmake /nologo clean
	cd feynman_5 & nmake /nologo clean
	cd feynman_6 & nmake /nologo clean
	cd feynman_7 & nmake /nologo clean
	cd feynman_8 & nmake /nologo clean
	cd feynman_9 & nmake /nologo clean
	cd feynman_shadow & nmake /nologo clean
	cd feynman_test & nmake /nologo clean
	cd fill & nmake /nologo clean
	cd fill-ft & nmake /nologo clean
	cd filters81 & nmake /nologo clean
	cd fitls & nmake /nologo clean
	cd fitz & nmake /nologo clean
	cd flow & nmake /nologo clean
	cd flux_linkage_space_vector_diagram & nmake /nologo clean
	cd four & nmake /nologo clean
	cd frequency & nmake /nologo clean
	cd fruitbar & nmake /nologo clean
	cd gc_color & nmake /nologo clean
	cd gc_join & nmake /nologo clean
	cd gc_write & nmake /nologo clean
	cd gradient & nmake /nologo clean
	cd h-bridge & nmake /nologo clean
	cd heatmap & nmake /nologo clean
	cd hello & nmake /nologo clean
	cd histogram & nmake /nologo clean
	cd horizon & nmake /nologo clean
	cd house & nmake /nologo clean
	cd hubble & nmake /nologo clean
	cd hyperbola & nmake /nologo clean
	cd informationgain & nmake /nologo clean
	cd inpstm & nmake /nologo clean
	cd intersect & nmake /nologo clean
	cd jitter & nmake /nologo clean
	cd join & nmake /nologo clean
	cd keyexamples & nmake /nologo clean
	cd koch & nmake /nologo clean
	cd labeled-scatter & nmake /nologo clean
	cd labels & nmake /nologo clean
	cd legend & nmake /nologo clean
	cd let-multi-dim & nmake /nologo clean
	cd lindenmayer & nmake /nologo clean
	cd line & nmake /nologo clean
	cd linemode & nmake /nologo clean
	cd lines & nmake /nologo clean
	cd lnx & nmake /nologo clean
	cd logo & nmake /nologo clean
	cd loop & nmake /nologo clean
	cd M16 & nmake /nologo clean
	cd M4_Re_Im & nmake /nologo clean
	cd mandelbrot & nmake /nologo clean
	cd margins & nmake /nologo clean
	cd markers & nmake /nologo clean
	cd math & nmake /nologo clean
	cd maungazoom & nmake /nologo clean
	cd mirrors & nmake /nologo clean
	cd mutation & nmake /nologo clean
	cd normal & nmake /nologo clean
	cd objects & nmake /nologo clean
	cd opening & nmake /nologo clean
	cd perceptron & nmake /nologo clean
	cd phasedemo & nmake /nologo clean
	cd playtennis_dt & nmake /nologo clean
	cd polarcircle & nmake /nologo clean
	cd polargrid & nmake /nologo clean
	cd polar_histogram & nmake /nologo clean
	cd polenja & nmake /nologo clean
	cd protract & nmake /nologo clean
	cd pythagoras & nmake /nologo clean
	cd pythagorean & nmake /nologo clean
	cd qgle_keyboard & nmake /nologo clean
	cd quantilescale & nmake /nologo clean
	cd radar & nmake /nologo clean
	cd ramps & nmake /nologo clean
	cd recursiontree & nmake /nologo clean
	cd regrmodel & nmake /nologo clean
	cd rt-y-is-x & nmake /nologo clean
	cd rugplot & nmake /nologo clean
	cd saddle & nmake /nologo clean
	cd saddle-contour & nmake /nologo clean
	cd sarppepo & nmake /nologo clean
	cd SdHmethod & nmake /nologo clean
	cd seaborn & nmake /nologo clean
	cd semitrans & nmake /nologo clean
	cd series & nmake /nologo clean
	cd shadebar & nmake /nologo clean
	cd shadow & nmake /nologo clean
	cd shapes & nmake /nologo clean
	cd shapes-ft & nmake /nologo clean
	cd sierpinski & nmake /nologo clean
	cd sin & nmake /nologo clean
	cd sine-approx & nmake /nologo clean
	cd spider & nmake /nologo clean
	cd sqroot & nmake /nologo clean
	cd square & nmake /nologo clean
	cd stack1 & nmake /nologo clean
	cd stack2 & nmake /nologo clean
	cd stack4b & nmake /nologo clean
	cd stack4c & nmake /nologo clean
	cd stacks & nmake /nologo clean
	cd steps & nmake /nologo clean
	cd stuff & nmake /nologo clean
	cd super-ellipse & nmake /nologo clean
	cd testaccents & nmake /nologo clean
	cd texgraph & nmake /nologo clean
	cd tgplot & nmake /nologo clean
	cd tree & nmake /nologo clean
	cd utitle & nmake /nologo clean
	cd volcano & nmake /nologo clean
	cd volcano-ft & nmake /nologo clean
	cd volcano3d & nmake /nologo clean
	cd wall & nmake /nologo clean
	cd wallx & nmake /nologo clean
	cd web & nmake /nologo clean
	cd winding & nmake /nologo clean
	cd windrose & nmake /nologo clean
	cd wulfnet & nmake /nologo clean
	cd zoom-in & nmake /nologo clean